#!/bin/bash

name="$1"
#checks if only 1 parameter given
if [ $# -ne 1 ]; then
	echo "Error: parameters problem"
	exit 1
fi
./P.sh "$name"
echo "in lock"
sleep 10
#Checks if user already exists
if [ -e "$name" ]; then
	echo "Error: user already exists"
	./V.sh "sema"
	exit 2
fi
#Make user directory
mkdir "$name"
echo "OK: user created"

./V.sh "$name"
exit 0
